/* Generated By:JavaCC: Do not edit this line. RBNParser2Constants.java */
package RBNio;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RBNParser2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOLtoken = 3;
  /** RegularExpression Id. */
  int EOL = 27;
  /** RegularExpression Id. */
  int CombinationFunction = 28;
  /** RegularExpression Id. */
  int WIFWIF = 29;
  /** RegularExpression Id. */
  int WIFTHEN = 30;
  /** RegularExpression Id. */
  int WIFELSE = 31;
  /** RegularExpression Id. */
  int COMBCOMB = 32;
  /** RegularExpression Id. */
  int COMBWITH = 33;
  /** RegularExpression Id. */
  int COMBFORALL = 34;
  /** RegularExpression Id. */
  int COMBWHERE = 35;
  /** RegularExpression Id. */
  int MULT = 36;
  /** RegularExpression Id. */
  int PLUS = 37;
  /** RegularExpression Id. */
  int Digits = 38;
  /** RegularExpression Id. */
  int Constant = 39;
  /** RegularExpression Id. */
  int Name = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOLtoken>",
    "\"%\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "<token of kind 8>",
    "\"@\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"#\"",
    "\"$\"",
    "\":\"",
    "\"{\"",
    "\"|\"",
    "\"}\"",
    "\"&\"",
    "\"true\"",
    "\"false\"",
    "\"~\"",
    "<EOL>",
    "<CombinationFunction>",
    "<WIFWIF>",
    "<WIFTHEN>",
    "<WIFELSE>",
    "<COMBCOMB>",
    "<COMBWITH>",
    "<COMBFORALL>",
    "<COMBWHERE>",
    "\"*\"",
    "\"+\"",
    "<Digits>",
    "<Constant>",
    "<Name>",
  };

}
