/* Generated By:JavaCC: Do not edit this line. RBNParserConstants.java */
package RBNio;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RBNParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOLtoken = 3;
  /** RegularExpression Id. */
  int EOL = 25;
  /** RegularExpression Id. */
  int CombinationFunction = 26;
  /** RegularExpression Id. */
  int WIFWIF = 27;
  /** RegularExpression Id. */
  int WIFTHEN = 28;
  /** RegularExpression Id. */
  int WIFELSE = 29;
  /** RegularExpression Id. */
  int COMBCOMB = 30;
  /** RegularExpression Id. */
  int COMBWITH = 31;
  /** RegularExpression Id. */
  int COMBFORALL = 32;
  /** RegularExpression Id. */
  int COMBWHERE = 33;
  /** RegularExpression Id. */
  int MULT = 34;
  /** RegularExpression Id. */
  int ProbabilityValue = 35;
  /** RegularExpression Id. */
  int Name = 36;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOLtoken>",
    "\"%\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "<token of kind 8>",
    "\"@\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"#\"",
    "\":\"",
    "\"{\"",
    "\"|\"",
    "\"}\"",
    "\"sformula(\"",
    "\"~\"",
    "\"&\"",
    "<EOL>",
    "<CombinationFunction>",
    "<WIFWIF>",
    "<WIFTHEN>",
    "<WIFELSE>",
    "<COMBCOMB>",
    "<COMBWITH>",
    "<COMBFORALL>",
    "<COMBWHERE>",
    "\"*\"",
    "<ProbabilityValue>",
    "<Name>",
  };

}
