/* Generated By:JavaCC: Do not edit this line. DBParserConstants.java */
package MLNParser.DBParser;

public interface DBParserConstants {

  int EOF = 0;
  int EOL = 7;
  int Variable = 8;
  int Constant = 9;
  int OpenPar = 10;
  int ClosePar = 11;
  int Not = 12;
  int Unknown = 13;

  int DEFAULT = 0;
  int WithinComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\",\"",
    "<EOL>",
    "<Variable>",
    "<Constant>",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"?\"",
  };

}
