/* Generated By:JavaCC: Do not edit this line. AtomListParserConstants.java */
package RBNio;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AtomListParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 7;
  /** RegularExpression Id. */
  int Name = 8;
  /** RegularExpression Id. */
  int Relation = 9;
  /** RegularExpression Id. */
  int Constant = 10;
  /** RegularExpression Id. */
  int OpenPar = 11;
  /** RegularExpression Id. */
  int ClosePar = 12;
  /** RegularExpression Id. */
  int Not = 13;
  /** RegularExpression Id. */
  int EndLiteral = 14;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\" \"",
    "<EOL>",
    "<Name>",
    "<Relation>",
    "<Constant>",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\".\"",
    "\",\"",
  };

}
