

options {
    STATIC = false ;
    FORCE_LA_CHECK = true;
	DEBUG_PARSER = false;
	DEBUG_LOOKAHEAD = false;
//	DEBUG_TOKEN_MANAGER = true;
	LOOKAHEAD = 3;
}


PARSER_BEGIN(RBNParser3)

package RBNio;

import PyManager.*;
import RBNpackage.*;
import java.util.*;
import RBNpackage.VarTermPackage.*;
import RBNExceptions.*;

public class RBNParser3{
	private int parseno = 1;
	private RBNReader3 reader;

}


PARSER_END(RBNParser3)


SKIP:{" " | "\t" | <EOLtoken:<EOL>>} // ignores blank spaces, tabs and end of lines

SKIP :
{
  "%" : WithinComment
}

<WithinComment> SKIP :
{
  "\n": DEFAULT
}
<WithinComment> SKIP :
{
  "\r\n": DEFAULT
}
<WithinComment> SKIP :
{
  "\r": DEFAULT
}

<WithinComment> MORE :
{
  <~[]>
}


void ReadRBN()  throws RBNIllegalArgumentException:
{}
{// grammar
	( MacroDefinition() | ProbRelDefinition() )+
}

// include "-" in Name
String ComplexName() :
{
    Token t;
    StringBuilder sb = new StringBuilder();
}
{
    t = <Name> { sb.append(t.image); }
    (
        <MINUS> t = <Name> { sb.append("-").append(t.image); }
    )*
    { return sb.toString(); }
}

void MacroDefinition()  throws RBNIllegalArgumentException:
{
    RBNReader3.ParsedTypedAtom parsedat;
    CPModel parsedprobform;
}
{// grammar
	"@" parsedat = TypedAtom(true) "="
	(
          // choose CatGnn only when COMPUTEWITHTORCH is next 
          LOOKAHEAD( <COMPUTEWITHTORCH> ) parsedprobform = ReadCatGnn(parsedat)
        |
          parsedprobform = ProbForm()
    )
    ";"
	{
        parsedat.set_relname("@"+parsedat.rel().name());
        switch  (parseno) {
        case 1:
            reader.addMacroDefined(new RBNMacro(((BoolRel)parsedat.rel()),parsedat.args(),null));
            break;
        case 2:
            reader.setMacroPF(parsedat.rel(),parsedprobform);
        }
	}
}

void ProbRelDefinition()  throws RBNIllegalArgumentException:
{
    RBNReader3.ParsedTypedAtom parsedat;
    CPModel parsedcpm;
}
{// grammar
	parsedat = TypedAtom(false) "=" parsedcpm = CPModel(parsedat) ";"
	{
        switch  (parseno)
        {
            case 1:
                reader.addProbRelDefined(new RBNPreldef(parsedat.rel(),parsedat.args(),parsedcpm));
                break;
            case 2:
            reader.setProbRelPF(parsedat.rel(),parsedcpm);
	    }
	}
}

CPModel CPModel(RBNReader3.ParsedTypedAtom contextAt)  throws RBNIllegalArgumentException:
{CPModel parsedcpm;}
{// grammar
    (parsedcpm = CatSoftMax() | parsedcpm = ProbForm() | parsedcpm = ReadCatGnn(contextAt))
    {return parsedcpm;}
}

CPModel ProbForm()  throws RBNIllegalArgumentException:
{CPModel parsedpf;
}
{// grammar
	( LOOKAHEAD(Atom() "=" ) parsedpf= BoolCatEquality()
	| LOOKAHEAD(ComplexName() "=" Atom()) parsedpf= BoolCatEquality()
 	| LOOKAHEAD(Atom()) parsedpf=Atom()
 	| LOOKAHEAD(<WIFWIF>) parsedpf = ConvCombinationCherry()
	| LOOKAHEAD(ConvCombination()) parsedpf=ConvCombination()
	| LOOKAHEAD(CombinationFunc()) parsedpf=CombinationFunc()
	| parsedpf=BoolFormula()
	| parsedpf=MacroCall()
	| parsedpf=Constant()
	)
	{return parsedpf;}
}

RBNReader3.ParsedUnTypedAtom UntypedAtom(boolean ismacro) throws RBNIllegalArgumentException:
{
  Vector<ArgTerm> args;
  String relname;
  Rel rel;
}
{// grammar
	relname = ComplexName()
    args = UntypedArguments()
	{
	 return reader.new ParsedUnTypedAtom(relname, args, ismacro);
	}
}

RBNReader3.ParsedTypedAtom TypedAtom(boolean ismacro) throws RBNIllegalArgumentException:
{
	RBNReader3.ParsedTypedArguments args;
	int arity;
	String relname;
}
{// grammar
	relname = ComplexName()
	args = TypedArguments()
	{arity = args.arity();
	 return  reader.new ParsedTypedAtom(relname,args,ismacro);
	}

}

Vector<ArgTerm> UntypedArguments():
{
    Vector<ArgTerm> parsedargs;
}
{// grammar
	"(" parsedargs = ArgList() ")"
	{ return parsedargs; }
}

Vector<ArgTerm> ArgList() :
{
    Vector<ArgTerm> parsedArgs = new Vector<ArgTerm>();
    ArgTerm t;
}
{
    (
        t = ArgExpr() { parsedArgs.add(t); }
        ( "," t = ArgExpr() { parsedArgs.add(t); } )*
    )?
    { return parsedArgs; }
}

ArgTerm ArgExpr() :
{
    ArgTerm left;
    ArgTerm right;
}
{
    left = ArgPrimary()
    (
        <PLUS> right = ArgPrimary() { left = new IntPlus(left, right); }
      | <MINUS> right = ArgPrimary() { left = new IntMinus(left, right); }
    )*
    { return left; }
}

ArgTerm ArgPrimary() :
{
    Token t;
    ArgTerm e;
}
{
    t = <Name> { return new VarTerm(t.image); }
  | t = <NonNegNumber> { return new VarTerm(t.image); }
  | "(" e = ArgExpr() ")" { return e; }
}


RBNReader3.ParsedTypedArguments TypedArguments():
{
	Token tok;
	Vector<ArgTerm> args = new Vector<ArgTerm>();
	Vector<Type> types = new Vector<Type>();
	String typestr = null;
}
{// grammar
	"("
	(
	    (typestr = TypeDeclaration())?
		{
            if (typestr != null)
            {
                types.add(new TypeRel(typestr));
                typestr = null;
            }
            else {types.add(new TypeDomain());}
		}
	    tok=<Name>
		{ args.add(new VarTerm(tok.image)); }

	    ( "," (typestr = TypeDeclaration())?
		{
            if (typestr != null) {
                types.add(new TypeRel(typestr));
                typestr = null;
			}
		    else {
                types.add(new TypeDomain());
            }
		}
	    tok=<Name>
		{ args.add(new VarTerm(tok.image)); }
	    )*
	) ?
	")"
	{ return reader.new ParsedTypedArguments(types,args); }
}

String TypeDeclaration():
{Token tok;}
{// grammar
	"[" tok = <Name> "]"
	{return tok.image;}
}


CPModel Constant():
{CPModel parsedpf;
}
{// grammar
	(parsedpf=NumericConstant() | parsedpf=Parameter())
	{return parsedpf;}
}

ProbFormConstant NumericConstant():
{ProbFormConstant parsedpfconst;
 Token tok;
}
{// grammar
	(tok = <NonNegNumber>
	{parsedpfconst = new ProbFormConstant(Double.parseDouble(tok.image));}
	|
	<MINUS> tok = <NonNegNumber>
	{parsedpfconst = new ProbFormConstant(-Double.parseDouble(tok.image));}
	)
	 {return parsedpfconst;}
}

ProbFormConstant  Parameter():
{ProbFormConstant parsedpfconst;
 String paramName;
 Token tok;}
{// grammar
	("#"
    paramName = ComplexName()
	 {return new ProbFormConstant("#" + paramName);}
	|
	"$" paramName = ComplexName()
	 {return new ProbFormConstant("$" + paramName);}
	)
}

CPModel Atom()  throws RBNIllegalArgumentException:
{
 ProbFormAtom parsedpfatom;
 RBNReader3.ParsedUnTypedAtom parsedutat;
 Rel parsedrel;
 Rel oldrel;
}
{// grammar
	parsedutat = UntypedAtom(false)
	{
	switch(parseno){
	case 1:
		reader.addAllRel(parsedutat.rel());
		return null;
		break;
	case 2:
	 	parsedrel = parsedutat.rel();
                // first need to look into reader.probrelsdefined in order
		// to ensure that the relation associated with the atom
		// is of type probabilistic
         	oldrel = reader.getProbRel(parsedrel);
                // if the following case triggers, then the relation
		// associated with the atom will be predefined
		if (oldrel == null)
		    oldrel = reader.getAllRel(parsedrel);
		return new ProbFormAtom(oldrel,parsedutat.args());
//	 	if (oldrel != null)
//		   return new ProbFormAtom(oldrel,StringOps.stringVectorToArray(parsedutat.args()));
//	 	else {
//		     oldrel = reader.getAllRel(parsedrel);
//		     return new ProbFormBoolAtom(oldrel,StringOps.stringVectorToArray(parsedutat.args()),true);
//		     }
	}
	}
}


ProbFormConvComb ConvCombination()  throws RBNIllegalArgumentException:
{ProbFormConvComb pf;
}
{
    ( LOOKAHEAD(<WIFWIF>) pf = ConvCombinationCherry()
    | pf = ConvCombinationClassic()
    )
	{switch(parseno){
	case 1:
		return null;
		break;
	case 2: return pf;
	}}
}

ProbFormConvComb ConvCombinationClassic()  throws RBNIllegalArgumentException:
{CPModel pf1;
 CPModel pf2;
 CPModel pf3;
}
{// grammar
	"(" pf1 = ProbForm()
        ":" pf2 = ProbForm()
        "," pf3 = ProbForm()
        ")"
	{switch(parseno){
	case 1:
		return null;
		break;
	case 2: return new ProbFormConvComb(pf1,pf2,pf3);
	}
	}
}

ProbFormConvComb ConvCombinationCherry()  throws RBNIllegalArgumentException:
{CPModel pf1;
 CPModel pf2;
 CPModel pf3;
}
{// grammar
	<WIFWIF>  pf1 = ProbForm() <WIFTHEN> pf2 = ProbForm() <WIFELSE> pf3 = ProbForm()
	{switch(parseno){
	case 1:
		return null;
		break;
	case 2: return new ProbFormConvComb(pf1,pf2,pf3);
	}
	}
}



ProbFormCombFunc CombinationFunc()  throws RBNIllegalArgumentException:
{ProbFormCombFunc pf;
}
{
	( pf = CombinationFuncClassic()
	| pf = CombinationFuncCherry()
	| LOOKAHEAD(CombinationFuncSum()) pf = CombinationFuncSum()
	| LOOKAHEAD(CombinationFuncProd()) pf = CombinationFuncProd()
	)
	{switch(parseno){
	case 1:
		return null;
		break;
	case 2: return pf;
	}}
}

ProbFormCombFunc CombinationFuncClassic()  throws RBNIllegalArgumentException:
{ Token tok;
  Vector<CPModel> pflist;
  Vector<ArgTerm> arglist;
  CPModel[] pfarr;
  ProbFormBool cc = new ProbFormBoolConstant(true);
}
{// grammar
	tok = <CombinationFunction> "{"
	pflist = ProbFormList() "|"
	arglist = ArgList() ":"
	(cc=BoolFormula())? "}"

	{switch(parseno){
	case 1:
		return null;
		break;
	case 2:
	 pfarr = new CPModel[pflist.size()];
	 for (int i=0;i<pfarr.length;i++)
		pfarr[i]=pflist.elementAt(i);
    ArgTerm[] argterms = arglist.toArray(new ArgTerm[0]);
    return new ProbFormCombFunc(tok.image,pfarr,argterms,cc);}
}
}


ProbFormCombFunc CombinationFuncCherry()  throws RBNIllegalArgumentException:
{ Token tok;
  Vector<CPModel> pflist;
  Vector<ArgTerm> arglist = new Vector<ArgTerm>();
  CPModel[] pfarr;
  ProbFormBool cc = new ProbFormBoolConstant(true);
}
{// grammar
	<COMBCOMB>
	pflist = ProbFormList()
	<COMBWITH>
	tok = <CombinationFunction>
	(<COMBFORALL>
	arglist = ArgList()
	<COMBWHERE> cc=BoolFormula())?

	{
    switch(parseno) {
        case 1:
            return null;
            break;
        case 2:
            pfarr = new CPModel[pflist.size()];
            for (int i=0;i<pfarr.length;i++)
                pfarr[i]=pflist.elementAt(i);
            ArgTerm[] argterms = arglist.toArray(new ArgTerm[0]);
            return new ProbFormCombFunc(tok.image,pfarr,argterms,cc);
    }
}
}

ProbFormCombFunc CombinationFuncProd()  throws RBNIllegalArgumentException:
{Vector<CPModel> pflist = new Vector<CPModel>();
CPModel nextpf;
CPModel[] pfarr;
}
{// grammar
    	"("
	nextpf = ProbForm()
	{pflist.add(nextpf);}
	(
	  <MULT> nextpf = ProbForm()
	   {pflist.add(nextpf);}
	)+
	")"
	{switch(parseno){
	case 1:
		return null;
		break;
	case 2:
	 pfarr = new CPModel[pflist.size()];
	 for (int i=0;i<pfarr.length;i++)
		pfarr[i]=pflist.elementAt(i);
	return new ProbFormCombFunc("prod",pfarr,new ArgTerm[0],new ProbFormBoolConstant(true));}
	}
}


ProbFormCombFunc CombinationFuncSum()  throws RBNIllegalArgumentException:
{Vector<CPModel> pflist = new Vector<CPModel>();
CPModel nextpf;
CPModel[] pfarr;
}
{// grammar
    	"("
	nextpf = ProbForm()
	{pflist.add(nextpf);}
	(

	  (<PLUS> nextpf = ProbForm(){
        pflist.add(nextpf);}
	   |
	   <MINUS> nextpf = ProbForm()
       	   {
           CPModel[] pfl = new CPModel[2];
       	   pfl[0]=new ProbFormConstant(-1);
       	   pfl[1]=nextpf;
       	   pflist.add(new ProbFormCombFunc("prod",pfl,new ArgTerm[0],new ProbFormBoolConstant(true)));
       	   }
       	)
	)+
	")"
	{switch(parseno){
	case 1:
		return null;
		break;
	case 2:
	 pfarr = new CPModel[pflist.size()];
	 for (int i=0;i<pfarr.length;i++)
		pfarr[i]=pflist.elementAt(i);
	return new ProbFormCombFunc("sum",pfarr,new ArgTerm[0],new ProbFormBoolConstant(true));}
	}
}


Vector<CPModel> ProbFormList()  throws RBNIllegalArgumentException:
{Vector<CPModel> pflist = new Vector<CPModel>();
 CPModel nextpf;
}
{// grammar
	( nextpf = ProbForm()
	  {pflist.add(nextpf);}
	("," nextpf = ProbForm()
	  {pflist.add(nextpf);}
	)*  )?
	{return pflist;}
}

ProbFormBool BoolPrimary()  throws RBNIllegalArgumentException:
{ProbFormBool pf;}
{// grammar
    ( LOOKAHEAD(ComplexName() "(") pf = BoolAtom()
    | LOOKAHEAD(ArgExpr() "=")  pf = BoolEquality()
    | LOOKAHEAD(ArgExpr() (<LT> | <GT>))  pf = BoolComparison()
    | LOOKAHEAD( "(" BoolFormula() "&"  )pf = BoolAnd()
    | LOOKAHEAD( "(" BoolFormula() "|"  )pf = BoolOr()
    | "(" pf = BoolFormula() ")"
    | pf = BoolConstant()
    | pf = BoolCatEquality()
    )
    {return pf;}
}

ProbFormBool BoolFormula() throws RBNIllegalArgumentException:
{ ProbFormBool pf; }
{
    ( pf = BoolNegation()
    | pf = BoolPrimary()
    )
    { return pf; }
}


ProbFormBoolAtom BoolAtom()  throws RBNIllegalArgumentException:
{RBNReader3.ParsedUnTypedAtom parsedat;
}
{// grammar
	parsedat = UntypedAtom(false)
	{return new ProbFormBoolAtom(parsedat.rel(), parsedat.args(), true);}
}


ProbFormBoolEquality BoolEquality()  throws RBNIllegalArgumentException:
{
 Token tok1;
 Token tok2;
 ArgTerm term1;
 ArgTerm term2;
}
{// grammar
    term1 = ArgExpr() "=" term2 = ArgExpr()
	{return new ProbFormBoolEquality(term1,term2,true);}
}

ProbFormBoolVarComparison BoolComparison() throws RBNIllegalArgumentException:
{
    ArgTerm term1;
    ArgTerm term2;
    Token op;
}
{// grammar
    term1 = ArgExpr() (op = <GT> | op = <LT>) term2 = ArgExpr()
    { return new ProbFormBoolVarComparison(term1, term2, op.image, true); }
}

ProbFormBoolAtomEquality BoolCatEquality() throws RBNIllegalArgumentException :
{
 Object tok1;
 Object tok2;
}
{// grammar
	(tok1=UntypedAtom(false) | tok1=ComplexName()) "=" (tok2=UntypedAtom(false) | tok2=ComplexName())
    {
        switch(parseno) {
        case 1:
            return null;
            break;
        case 2:
             if (tok1 instanceof RBNReader3.ParsedUnTypedAtom){
                tok1= new ProbFormAtom(((RBNReader3.ParsedUnTypedAtom)tok1).rel(),((RBNReader3.ParsedUnTypedAtom)tok1).args());
        }
             if (tok2 instanceof RBNReader3.ParsedUnTypedAtom){
                tok2= new ProbFormAtom(((RBNReader3.ParsedUnTypedAtom)tok2).rel(),((RBNReader3.ParsedUnTypedAtom)tok2).args());
        }
             return new ProbFormBoolAtomEquality(tok1,tok2,true,reader.getSig());
        }
    }
}

ProbFormBoolComposite BoolAnd()  throws RBNIllegalArgumentException:
{Vector<ProbFormBool> comps=new Vector<ProbFormBool>() ;
ProbFormBool nextpfb;}
{//grammar
	"("
	nextpfb = BoolFormula()
	{comps.add(nextpfb);}
	(
	  "&" 	nextpfb = BoolFormula()
	   {comps.add(nextpfb);}
	)+
	")"
{return new ProbFormBoolComposite(comps,ProbFormBool.OPERATORAND,true);}
}

ProbFormBoolComposite BoolOr()  throws RBNIllegalArgumentException:
{Vector<ProbFormBool> comps=new Vector<ProbFormBool>();
ProbFormBool nextpfb;}
{//grammar
	"("
	nextpfb = BoolFormula()
	{comps.add(nextpfb);}
	(
	  "|" 	nextpfb = BoolFormula()
	   {comps.add(nextpfb);}
	)+
	")"
{return new ProbFormBoolComposite(comps,ProbFormBool.OPERATOROR,true);}
}


ProbFormBoolConstant BoolConstant():
{}
{ //grammar
	("true" {return new ProbFormBoolConstant(true);}
	|
	"false" {return new ProbFormBoolConstant(false);}
	)
}


ProbFormBool BoolNegation()  throws RBNIllegalArgumentException:
{ProbFormBool pfb;}
{ //grammar
  "~" pfb = BoolPrimary()
  {pfb.toggleSign();
  return pfb;}
}


ProbFormMacroCall MacroCall()  throws RBNIllegalArgumentException:
{
 RBNReader3.ParsedUnTypedAtom parsedat;
 RBNMacro macrodef;
}
{// grammar
	"@" parsedat =  UntypedAtom(true)
	{
	// Add the '@' back to the name:
	parsedat.set_relname("@"+parsedat.rel().name());
	switch(parseno){
		case 1:
			return null;
			break;
		case 2:
	  		macrodef = reader.getMacroDef(parsedat.rel());
	  		if (macrodef != null)
			return new ProbFormMacroCall(macrodef,parsedat.args());
	  else throw new ParseException("Macro @" + parsedat.rel().name.name + " undefined");
		}
	}

}

CatModelSoftMax CatSoftMax()  throws RBNIllegalArgumentException:
{
  Vector<CPModel> pflist;
}
{// grammar
     <SOFTMAX>	pflist = ProbFormList()
     {switch(parseno){
	case 1:
		return null;
		break;
	case 2:
	     return new CatModelSoftMax(pflist);
	}
	}
}

List<Rel> AttrList() throws RBNIllegalArgumentException:
{
    ArrayList<Rel> attrs = new ArrayList<>();
    String attr;
    Token tk;
    RBNReader3.ParsedTypedAtom parsedat;
    Rel r;
}
{
    attr = ComplexName()
    {
        r = reader.getRelFromSignature(attr);
        attrs.add(r);
    }
    (
        ","
        attr = ComplexName()
        {
            r = reader.getRelFromSignature(attr);
            attrs.add(r);
        }
    )*
    { return attrs; }
}

String PathDec():
{Token tok;}
{
	"[" tok = <Path> "]"
	{return tok.image;}
}

TorchInputPf CombinationTorchRels() throws RBNIllegalArgumentException:
{
    Token tok;
    Vector<CPModel> pflistNodeFeat = new Vector<>();
    Vector<CPModel> pflistEdgeGraph = new Vector<>();
    Vector<CPModel> pflistEdgeAttr = new Vector<>();
    Vector<ArgTerm> arglist = new Vector<ArgTerm>();
    CPModel[] pfarr;
    CPModel[] pfarrNodeAttr;
    CPModel[] pfarrEdge;
    CPModel[] pfarrEdgeAttr;
    ProbFormBool cc = new ProbFormBoolConstant(true);
}
{// grammar
    <COMBCOMB>
    <NODEFEAT> pflistNodeFeat = ProbFormList()
    (<EDGEGRAPH> pflistEdgeGraph = ProbFormList())?
    (<EDGEATTR> pflistEdgeAttr = ProbFormList())?
    <USINGTORCH>
    (<COMBFORALL> arglist = ArgList() <COMBWHERE> cc=BoolFormula())?
    {
    switch(parseno) {
        case 1: return null; break;
        case 2:
            pfarr = new CPModel[pflistNodeFeat.size()+pflistEdgeGraph.size()+pflistEdgeAttr.size()];
            pfarrNodeAttr = new CPModel[pflistNodeFeat.size()];
            pfarrEdge = new CPModel[pflistEdgeGraph.size()];
            pfarrEdgeAttr = new CPModel[pflistEdgeAttr.size()];
            int indexAll = 0;
            for (int i=0;i<pflistNodeFeat.size();i++, indexAll++){
                pfarr[indexAll]=pflistNodeFeat.elementAt(i);
                pfarrNodeAttr[i]=pflistNodeFeat.elementAt(i);
            }
            for (int i=0;i<pflistEdgeGraph.size();i++, indexAll++){
                pfarr[indexAll]=pflistEdgeGraph.elementAt(i);
                pfarrEdge[i]=pflistEdgeGraph.elementAt(i);
            }
            for (int i=0;i<pflistEdgeAttr.size();i++, indexAll++){
                pfarr[indexAll]=pflistEdgeAttr.elementAt(i);
                pfarrEdgeAttr[i]=pflistEdgeAttr.elementAt(i);
            }
            return new TorchInputPf(pfarr, pfarrNodeAttr, pfarrEdge, pfarrEdgeAttr, arglist.toArray(new ArgTerm[0]),cc);
        }
    }
}

CatGnn ReadCatGnn(RBNReader3.ParsedTypedAtom parsedat) throws RBNIllegalArgumentException :
{
    Token tk1 = null;
    String tk2;
    ArgTerm[] freeVals;
    Type[] outTypes;
    String configPath;
    int numVals = 1;
    List<TorchInputSpecs> forInputs = new ArrayList<>();
    List<Rel> attrs;
    List<Rel> edgeAttrs = new ArrayList<>();
    BoolRel edgeRel;
    TypedTorchPf tti = new TypedTorchPf();
    TorchInputPf tri;
    List<List<TorchInputPf>> combineClausesType = new ArrayList<>();
}
{
    <COMPUTEWITHTORCH>
    configPath = PathDec()
//    <WithNumValues>
//    tk1 = <NonNegNumber> { numVals = Integer.parseInt(tk1.image); }
//    <ForFreeVars>
//    freeVals = UntypedArguments()
//    <ForOutTypes>
//    outTypes = UntypedArguments()
{
    numVals = (int) parsedat.rel().numvals();
    if (parsedat.rel() instanceof BoolRel)
        numVals=1;
    freeVals = parsedat.args();
    outTypes = parsedat.pargs.types();
}

    (
        <TYPEDICT>
            <NODEFEAT> attrs = AttrList()
            <EDGEGRAPH> tk2 = ComplexName()
            (
                <EDGEATTR> edgeAttrs = AttrList()
            )?
            {
                edgeRel = (BoolRel) reader.getRelFromSignature(tk2);
                if (edgeAttrs.size() > 0) {
                    TorchInputSpecs tis = new TorchInputSpecs(attrs.get(0).getTypesAsString(), attrs, edgeRel, edgeAttrs);
                    forInputs.add(tis);
                } else {
                    TorchInputSpecs tis = new TorchInputSpecs(attrs.get(0).getTypesAsString(), attrs, edgeRel, null);
                    forInputs.add(tis);
                }
            }

            {List<TorchInputPf> combineClauses = new ArrayList<>();}

            tri = CombinationTorchRels()
            {
                combineClauses.add(tri);
            }
            (
                ","
                tri = CombinationTorchRels()
                {
                    combineClauses.add(tri);
                }
            )*
            {
                combineClausesType.add(combineClauses);
                tti.addCombine(attrs.get(0).getTypesAsString(), combineClauses);
            }
    )+

    {
        switch(parseno)
        {
            case 1:
                return null;
                break;
            case 2:
                if (numVals == 1)
                    return new CatGnnBool(configPath, freeVals, forInputs, tti, outTypes, true);
                return new CatGnn(configPath, freeVals, numVals, forInputs, tti, outTypes, true);
        }
    }
}


TOKEN:{
	<EOL: "\n" | "\r" | "\r\n">
}


TOKEN:{
	<CombinationFunction: "n-or"|"mean"|"esum"|"invsum"|"l-reg"|"ll-reg"|"sum"|"prod" >
}

TOKEN:{
	<WIFWIF: "WIF" | "wif" | "Wif" >
}

TOKEN:{
	<WIFTHEN: "THEN" | "then" | "Then" >
}

TOKEN:{
	<WIFELSE: "ELSE" | "else" | "Else" >
}

TOKEN:{
	<COMBCOMB: "COMBINE" | "combine" | "Combine" >
}

TOKEN:{
	<COMBWITH: "WITH" | "with" | "With" >
}

TOKEN:{
	<COMBFORALL: "FORALL" | "forall" | "Forall" >
}

TOKEN:{
	<COMBWHERE: "WHERE" | "where" | "Where" >
}


TOKEN:{
	<SOFTMAX: "SOFTMAX" | "Softmax" | "softmax" >
}

TOKEN : {
    <COMPUTEWITHTORCH: "COMPUTEWITHTORCH" | "ComputeWithTorch" | "computewithtorch" >
}

TOKEN : {
    <UsingRels: "USINGRELS" | "UsingRels" | "usingrels" >
}

TOKEN : {
    <FORNUMLAYERS: "FORNUMLAYERS" | "ForNumLayers" | "fornumlayers" >
}

TOKEN : {
    <ForFreeVars: "FORFREEVARS" | "ForFreeVars" | "forfreevars" >
}

TOKEN : {
    <ForOutTypes: "FOROUTTYPES" | "ForOutTypes" | "forouttypes" >
}

TOKEN : {
    <WithNumValues: "WITHNUMVALUES" | "WithNumValues" | "withnumvalues" >
}

TOKEN: {
    <TYPEDICT: "TYPEDICT" | "TypeDict" | "typedict" >
}

TOKEN: {
    <NODEFEAT: "NodeFeat" | "NODEFEAT" | "nodefeat" >
}

TOKEN : {
    <EDGEGRAPH: "EDGEGRAPH" | "EdgeGraph" | "edgegraph" >
}

TOKEN : {
    <EDGEATTR: "EDGEATTR" | "EdgeAttr" | "edgeattr" >
}

TOKEN:{
	<USINGTORCH: "usingtorch" | "USINGTORCH" | "UsingTorch" | "Usingtorch" >
}

TOKEN : {
    <Name: ["a"-"z","A"-"Z"] (["a"-"z","A"-"Z","0"-"9","_"])* >
}

//TOKEN : {
//    < Path: "/" ( ["a"-"z", "A"-"Z", "0"-"9", "_", "-", ".", "/"] )+ >
//}

TOKEN : {
    /* Windows: e.g. C:\dir\file.ext
       or   Unix:   /home/user/file.ext
       (no spaces or brackets allowed inside) */
    < Path:
      (
         ( ["A"-"Z","a"-"z"] ":" ( ["\\","/","a"-"z","A"-"Z","0"-"9",".","_","-"] )+ )
       | ( "/" (~[" ", "\t", "\r", "\n", "[", "]"])+ )
      )
    >
}


TOKEN:{
	<MULT: "*" >
}
TOKEN:{
	<PLUS: "+" >
}

TOKEN:{
	<MINUS: "-" >
}

TOKEN:{
	<GT: ">" >
}

TOKEN:{
	<LT: "<" >
}
//TOKEN: {<ProbabilityValue: ("0"|"1") ("." (["0"-"9"])*)?
//			   | "." (["0"-"9"])+ >
//}

TOKEN: {<#Digits: (["0"-"9"])+>}

TOKEN: {<NonNegNumber: <Digits> | "."<Digits> | <Digits> "."<Digits> | <Digits> ".">}

//TOKEN: {<Constant:  (<MINUS>)?  (<Digits> | "."<Digits> | <Digits> "."<Digits> | <Digits> ".")>
//}

// Java functions

void setReader(RBNReader3 rdr):
{}
{
	{reader = rdr;}
}

void setParseno(int pn):
{}
{
	{parseno = pn;}
}
