/* Generated By:JavaCC: Do not edit this line. RBNParser3Constants.java */
package RBNio;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RBNParser3Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOLtoken = 3;
  /** RegularExpression Id. */
  int EOL = 27;
  /** RegularExpression Id. */
  int CombinationFunction = 28;
  /** RegularExpression Id. */
  int WIFWIF = 29;
  /** RegularExpression Id. */
  int WIFTHEN = 30;
  /** RegularExpression Id. */
  int WIFELSE = 31;
  /** RegularExpression Id. */
  int COMBCOMB = 32;
  /** RegularExpression Id. */
  int COMBWITH = 33;
  /** RegularExpression Id. */
  int COMBFORALL = 34;
  /** RegularExpression Id. */
  int COMBWHERE = 35;
  /** RegularExpression Id. */
  int SOFTMAX = 36;
  /** RegularExpression Id. */
  int COMPUTEWITHTORCH = 37;
  /** RegularExpression Id. */
  int UsingRels = 38;
  /** RegularExpression Id. */
  int FORNUMLAYERS = 39;
  /** RegularExpression Id. */
  int ForFreeVars = 40;
  /** RegularExpression Id. */
  int ForOutTypes = 41;
  /** RegularExpression Id. */
  int WithNumValues = 42;
  /** RegularExpression Id. */
  int TYPEDICT = 43;
  /** RegularExpression Id. */
  int NODEFEAT = 44;
  /** RegularExpression Id. */
  int EDGEGRAPH = 45;
  /** RegularExpression Id. */
  int EDGEATTR = 46;
  /** RegularExpression Id. */
  int USINGTORCH = 47;
  /** RegularExpression Id. */
  int Name = 48;
  /** RegularExpression Id. */
  int Path = 49;
  /** RegularExpression Id. */
  int MULT = 50;
  /** RegularExpression Id. */
  int PLUS = 51;
  /** RegularExpression Id. */
  int MINUS = 52;
  /** RegularExpression Id. */
  int GT = 53;
  /** RegularExpression Id. */
  int LT = 54;
  /** RegularExpression Id. */
  int Digits = 55;
  /** RegularExpression Id. */
  int NonNegNumber = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOLtoken>",
    "\"%\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "<token of kind 8>",
    "\"@\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"#\"",
    "\"$\"",
    "\":\"",
    "\"{\"",
    "\"|\"",
    "\"}\"",
    "\"&\"",
    "\"true\"",
    "\"false\"",
    "\"~\"",
    "<EOL>",
    "<CombinationFunction>",
    "<WIFWIF>",
    "<WIFTHEN>",
    "<WIFELSE>",
    "<COMBCOMB>",
    "<COMBWITH>",
    "<COMBFORALL>",
    "<COMBWHERE>",
    "<SOFTMAX>",
    "<COMPUTEWITHTORCH>",
    "<UsingRels>",
    "<FORNUMLAYERS>",
    "<ForFreeVars>",
    "<ForOutTypes>",
    "<WithNumValues>",
    "<TYPEDICT>",
    "<NODEFEAT>",
    "<EDGEGRAPH>",
    "<EDGEATTR>",
    "<USINGTORCH>",
    "<Name>",
    "<Path>",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\">\"",
    "\"<\"",
    "<Digits>",
    "<NonNegNumber>",
  };

}
