/* Generated By:JavaCC: Do not edit this line. MLNParser.java */
package MLNParser.MLNParser;

//import java.io.*;
import RBNpackage.ProbForm;
import MLNExceptions.NoSuchRelationException;
import MLNExceptions.BadArityException;
import MLNParser.*;
import java.util.Vector;


public class MLNParser implements MLNParserConstants {
        private RBNCreator creator;
        private int parseno = 0;

  final public void ReadMarkovLogicNetwork() throws ParseException {
    RelationList();
    label_1:
    while (true) {
      if (jj_2_1(3)) {
        ;
      } else {
        break label_1;
      }
      jj_consume_token(EOL);
    }
    TypeDeclarationList();
    label_2:
    while (true) {
      if (jj_2_2(3)) {
        ;
      } else {
        break label_2;
      }
      jj_consume_token(EOL);
    }
    HardFormulaList();
    label_3:
    while (true) {
      if (jj_2_3(3)) {
        ;
      } else {
        break label_3;
      }
      jj_consume_token(EOL);
    }
    WeightFormulaList();
    label_4:
    while (true) {
      if (jj_2_4(3)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(EOL);
    }
         if (parseno==3)
                creator.fileFinished();
    jj_consume_token(0);
  }

//Relations
  final public void RelationList() throws ParseException {
 //variables
        ProbForm formula;
    label_5:
    while (true) {
      if (jj_2_5(3)) {
        ;
      } else {
        break label_5;
      }
      RelationDeclared();
      jj_consume_token(EOL);
    }
  }

  final public ProbForm RelationDeclared() throws ParseException {
 //variables
        Token tok;
        ProbForm formula;
        ParsedRelation relation=new ParsedRelation();
    //grammar
            tok = jj_consume_token(Variable);
                //relationName=tok.image;
                relation = new ParsedRelation(tok.image);
    jj_consume_token(OpenPar);
    tok = jj_consume_token(Variable);
                relation.addArgument(tok.image);
    label_6:
    while (true) {
      if (jj_2_6(3)) {
        ;
      } else {
        break label_6;
      }
      jj_consume_token(6);
      tok = jj_consume_token(Variable);
                relation.addArgument(tok.image);
    }
    jj_consume_token(ClosePar);
                formula = null;
                if (parseno==1)
                        creator.createRelation(relation);
                {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

  final public void TypeDeclarationList() throws ParseException {
    label_7:
    while (true) {
      if (jj_2_7(3)) {
        ;
      } else {
        break label_7;
      }
      TypeDeclaration();
      label_8:
      while (true) {
        jj_consume_token(EOL);
        if (jj_2_8(3)) {
          ;
        } else {
          break label_8;
        }
      }
    }
  }

  final public void TypeDeclaration() throws ParseException {
 //variables
        Token typeTok,constTok;
    //grammar
            typeTok = jj_consume_token(Variable);
        if (parseno==1)
                creator.newTypeDeclared(typeTok.image);
    jj_consume_token(7);
    jj_consume_token(8);
    constTok = jj_consume_token(Constant);
        if (parseno==1)
                creator.insertTypeConstant(typeTok.image,constTok.image);
    label_9:
    while (true) {
      if (jj_2_9(3)) {
        ;
      } else {
        break label_9;
      }
      jj_consume_token(6);
      constTok = jj_consume_token(Constant);
        if (parseno==1)
                creator.insertTypeConstant(typeTok.image,constTok.image);
    }
    jj_consume_token(9);
  }

//Hard formulas
  final public void HardFormulaList() throws ParseException {
 //variables
        ProbForm formula;
    label_10:
    while (true) {
      if (jj_2_10(3)) {
        ;
      } else {
        break label_10;
      }
      formula = HardFormula();
      jj_consume_token(10);
      label_11:
      while (true) {
        jj_consume_token(EOL);
        if (jj_2_11(3)) {
          ;
        } else {
          break label_11;
        }
      }
                if(parseno==2)
                        creator.addNewRelationFormula(formula);
    }
  }

  final public ProbForm HardFormula() throws ParseException {
 //variables
        ProbForm formula = null;
    //grammar
            formula = Formula_1();
                if(parseno == 3){
                        creator.newFormulaForArtificial();
                        {if (true) return null;}
                }
                else if(parseno == 2){
                        formula = creator.createWeightFormula(formula, "");
                        {if (true) return formula;}
                }
        {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

// A Formula_i is a formula of the form 
// f1 op1 f2 op2 ... opn-1 fn
// where the fi are either atomic formulas or sub-formulas
// that are enclosed in parentheses, the opi are boolean 
// operators, and the operator with the lowest precedence 
// among op1,...,opn-1 is
// i=1: <=>
// i=2: =>
// i=3: v
// i=4: ^
  final public ProbForm Formula_1() throws ParseException {
 //variables
        ProbForm formula = null;
        ProbForm secondPart;
    //grammar
            formula = Formula_2();
    label_12:
    while (true) {
      if (jj_2_12(3)) {
        ;
      } else {
        break label_12;
      }
      jj_consume_token(IfAndOnlyIf);
      secondPart = Formula_2();
          if (parseno==2)
                formula = creator.createIfOnlyIf(formula, secondPart);
    }
         {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

  final public ProbForm Formula_2() throws ParseException {
 //variables 
        ProbForm formula = null;
        ProbForm secondPart;
    //grammar
            formula = Formula_3();
    label_13:
    while (true) {
      if (jj_2_13(3)) {
        ;
      } else {
        break label_13;
      }
      jj_consume_token(Implies);
      secondPart = Formula_3();
          if (parseno==2)
                        formula = creator.createImplies(formula,secondPart);
    }
         {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

  final public ProbForm Formula_3() throws ParseException {
 //variables 
        ProbForm formula = null;
        ProbForm secondPart;
    //grammar
            formula = Formula_4();
    label_14:
    while (true) {
      if (jj_2_14(3)) {
        ;
      } else {
        break label_14;
      }
      jj_consume_token(Or);
      secondPart = Formula_4();
          if (parseno==2)
                        formula = creator.createOr(formula,secondPart);
    }
         {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

  final public ProbForm Formula_4() throws ParseException {
 //variables 
        ProbForm formula = null;
        ProbForm secondPart;
    //grammar
            formula = Formula();
    label_15:
    while (true) {
      if (jj_2_15(3)) {
        ;
      } else {
        break label_15;
      }
      jj_consume_token(And);
      secondPart = Formula();
          if (parseno==2)
                        formula = creator.createAnd(formula,secondPart);
    }
         {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

  final public ProbForm Formula() throws ParseException {
 //variables
        Token tok;
        ProbForm formula = null;
        ParsedRelation relation=new ParsedRelation();
        Vector<String> quantargs = new Vector<String>();
        String equalityvar1 = "";
        String equalityvar2 = "";
    if (jj_2_19(3)) {
      jj_consume_token(Not);
      formula = Formula();
          if (parseno==2){
                formula = creator.createNot(formula);
                }
    } else if (jj_2_20(3)) {
      jj_consume_token(Exist);
      tok = jj_consume_token(Variable);
          if (parseno==2){
                        quantargs.add(tok.image);
                }
      label_16:
      while (true) {
        if (jj_2_16(3)) {
          ;
        } else {
          break label_16;
        }
        jj_consume_token(6);
        tok = jj_consume_token(Variable);
          if (parseno==2){
                        quantargs.add(tok.image);
                }
      }
      formula = Formula();
                  if (parseno==2){
                        formula = creator.createExistential(formula,quantargs);
                }
    } else if (jj_2_21(3)) {
      jj_consume_token(Forall);
      tok = jj_consume_token(Variable);
          if (parseno==2){
                        quantargs.add(tok.image);
                }
      label_17:
      while (true) {
        if (jj_2_17(3)) {
          ;
        } else {
          break label_17;
        }
        jj_consume_token(6);
        tok = jj_consume_token(Variable);
          if (parseno==2){
                        quantargs.add(tok.image);
                }
      }
      formula = Formula();
                  if (parseno==2){
                        formula = creator.createUniversal(formula,quantargs);
                }
    } else if (jj_2_22(3)) {
      jj_consume_token(OpenPar);
      formula = Formula_1();
      jj_consume_token(ClosePar);

    } else if (jj_2_23(3)) {
      //Atom
              tok = jj_consume_token(Variable);
          if (parseno>=2){
                relation = new ParsedRelation(tok.image);
                }
      jj_consume_token(OpenPar);
      tok = jj_consume_token(Variable);
                  if (parseno>=2){
                relation.addArgument(tok.image);
                }
      label_18:
      while (true) {
        if (jj_2_18(3)) {
          ;
        } else {
          break label_18;
        }
        jj_consume_token(6);
        tok = jj_consume_token(Variable);
                          if (parseno>=2){
                relation.addArgument(tok.image);
                }
      }
      jj_consume_token(ClosePar);
                        if (parseno==3){
                                creator.saveRelationForArtificial(relation);
                        }
                        else if (parseno==2){
                                try{
                                        formula = creator.createFormulaRelation(relation);
                                }catch(NoSuchRelationException e){
                                        System.out.println("The " +relation.getRelationName() + " relation is not valid");
                                        e.printStackTrace();
                                }catch(BadArityException e){
                                        System.out.print("The relation " + relation.getRelationName()+"(");
                                        String[] arg = relation.getArgumentsArray();
                                        for(int i=0;i<arg.length-1;i++)
                                                System.out.print(arg[i]+",");
                                        System.out.print(arg[arg.length-1]);
                                        System.out.println(") has not the same arity as declared");
                                        e.printStackTrace();
                                        System.exit(1);
                                }
                                }
    } else if (jj_2_24(3)) {
      // Equality Atom
              tok = jj_consume_token(Variable);
                if (parseno==2){
                        equalityvar1 = tok.image;
                }
      jj_consume_token(7);
      tok = jj_consume_token(Variable);
                if (parseno==2){
                        equalityvar2 = tok.image;
                }
                if (parseno==2){
                        formula = creator.createFormulaEquality(equalityvar1,equalityvar2);
                }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

//Weight Formulas
  final public void WeightFormulaList() throws ParseException {
 //variables
        ProbForm formula;
        Token t;
    label_19:
    while (true) {
      if (jj_2_25(3)) {
        ;
      } else {
        break label_19;
      }
      formula = WeightFormula();
      label_20:
      while (true) {
        jj_consume_token(EOL);
        if (jj_2_26(3)) {
          ;
        } else {
          break label_20;
        }
      }
                if(parseno==2)
                        creator.addNewRelationFormula(formula);
    }
  }

  final public ProbForm WeightFormula() throws ParseException {
 //variables
        Token t;
        ProbForm formula = null;
    //grammar
            t = jj_consume_token(Weight);
    formula = Formula_1();
                if(parseno == 3){
                        creator.newFormulaForArtificial();
                        {if (true) return null;}
                }
                else if(parseno == 2){
                        formula = creator.createWeightFormula(formula, t.image);
                        {if (true) return formula;}
                }
        {if (true) return formula;}
    throw new Error("Missing return statement in function");
  }

//java functions
  final public void setCreator(RBNCreator c) throws ParseException {
         creator = c;
  }

  final public void setParse(int i) throws ParseException {
         parseno = i;
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_3_20() {
    if (jj_scan_token(Exist)) return true;
    if (jj_scan_token(Variable)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_16()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(EOL)) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_scan_token(EOL)) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(Variable)) return true;
    if (jj_scan_token(OpenPar)) return true;
    if (jj_scan_token(Variable)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_scan_token(And)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_scan_token(OpenPar)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_scan_token(Not)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) {
    jj_scanpos = xsp;
    if (jj_3_24()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_24() {
    if (jj_scan_token(Variable)) return true;
    if (jj_scan_token(7)) return true;
    if (jj_scan_token(Variable)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(Weight)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(Or)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(Variable)) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(Variable)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_scan_token(Forall)) return true;
    if (jj_scan_token(Variable)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_17()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(Implies)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(Variable)) return true;
    if (jj_scan_token(OpenPar)) return true;
    if (jj_scan_token(Variable)) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(Constant)) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(EOL)) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(Variable)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(EOL)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(EOL)) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(EOL)) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(Variable)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(EOL)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(Variable)) return true;
    if (jj_scan_token(7)) return true;
    if (jj_scan_token(8)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(IfAndOnlyIf)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MLNParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos;
private Token jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[26];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MLNParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MLNParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MLNParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MLNParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MLNParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MLNParser(MLNParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MLNParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[27];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 27; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 26; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
