/* Generated By:JavaCC: Do not edit this line. MLNParserConstants.java */
package MLNParser.MLNParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MLNParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 13;
  /** RegularExpression Id. */
  int Not = 14;
  /** RegularExpression Id. */
  int And = 15;
  /** RegularExpression Id. */
  int Or = 16;
  /** RegularExpression Id. */
  int Implies = 17;
  /** RegularExpression Id. */
  int IfAndOnlyIf = 18;
  /** RegularExpression Id. */
  int OpenPar = 19;
  /** RegularExpression Id. */
  int ClosePar = 20;
  /** RegularExpression Id. */
  int Exist = 21;
  /** RegularExpression Id. */
  int Forall = 22;
  /** RegularExpression Id. */
  int Weight = 23;
  /** RegularExpression Id. */
  int Num = 24;
  /** RegularExpression Id. */
  int Variable = 25;
  /** RegularExpression Id. */
  int Constant = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\",\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "\"!\"",
    "\"^\"",
    "\"v\"",
    "\"=>\"",
    "\"<=>\"",
    "\"(\"",
    "\")\"",
    "<Exist>",
    "<Forall>",
    "<Weight>",
    "<Num>",
    "<Variable>",
    "<Constant>",
  };

}
