/* Generated By:JavaCC: Do not edit this line. RBNParser3.java */
package RBNio;

import RBNpackage.*;
import java.util.*;
import myio.StringOps;
import RBNExceptions.RBNSyntaxException;

public class RBNParser3 implements RBNParser3Constants {
        private int parseno = 1;
        private RBNReader3 reader;

  final public void ReadRBN() throws ParseException {
    trace_call("ReadRBN");
    try {
      label_1:
      while (true) {
        if (jj_2_1(3)) {
          MacroDefinition();
        } else if (jj_2_2(3)) {
          ProbRelDefinition();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        if (jj_2_3(3)) {
          ;
        } else {
          break label_1;
        }
      }
    } finally {
      trace_return("ReadRBN");
    }
  }

  final public void MacroDefinition() throws ParseException {
    trace_call("MacroDefinition");
    try {
 RBNReader3.ParsedTypedAtom parsedat;
 ProbForm parsedprobform;
      jj_consume_token(9);
      parsedat = TypedAtom();
      jj_consume_token(10);
      parsedprobform = ProbForm();
      jj_consume_token(11);
         // Add the '@' back to the name:
        parsedat.set_relname("@"+parsedat.rel().name());
        switch  (parseno){
        case 1:
                reader.addMacroDefined(new RBNMacro(parsedat.rel(),parsedat.args(),null));
                break;
        case 2:
                reader.setMacroPF(parsedat.rel(),parsedprobform);
        }
    } finally {
      trace_return("MacroDefinition");
    }
  }

  final public void ProbRelDefinition() throws ParseException {
    trace_call("ProbRelDefinition");
    try {
 RBNReader3.ParsedTypedAtom parsedat;
 ProbForm parsedprobform;
      // grammar
              parsedat = TypedAtom();
      jj_consume_token(10);
      parsedprobform = ProbForm();
      jj_consume_token(11);
         switch  (parseno){
                case 1:
                        reader.addProbRelDefined(new RBNPreldef(parsedat.rel(),parsedat.args(),null));
                        break;
                case 2:
                reader.setProbRelPF(parsedat.rel(),parsedprobform);
        }
    } finally {
      trace_return("ProbRelDefinition");
    }
  }

  final public ProbForm ProbForm() throws ParseException {
    trace_call("ProbForm");
    try {
 ProbForm parsedpf;
      if (jj_2_4(3)) {
        parsedpf = Constant();
      } else if (jj_2_5(2147483647)) {
        parsedpf = Atom();
      } else if (jj_2_6(2147483647)) {
        parsedpf = ConvCombination();
      } else if (jj_2_7(2147483647)) {
        parsedpf = CombinationFunc();
      } else if (jj_2_8(3)) {
        parsedpf = BoolFormula();
      } else if (jj_2_9(3)) {
        parsedpf = MacroCall();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
         {if (true) return parsedpf;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ProbForm");
    }
  }

  final public RBNReader3.ParsedUnTypedAtom UntypedAtom() throws ParseException {
    trace_call("UntypedAtom");
    try {
  Vector<String> args;
  Token tok;
  Rel rel;
      // grammar
              tok = jj_consume_token(Name);
      args = UntypedArguments();
         rel = new Rel(tok.image,args.size());
         {if (true) return reader.new ParsedUnTypedAtom(rel,args);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("UntypedAtom");
    }
  }

  final public RBNReader3.ParsedTypedAtom TypedAtom() throws ParseException {
    trace_call("TypedAtom");
    try {
        Token tok;
        RBNReader3.ParsedTypedArguments args;
        BoolRel rel;
        int arity;
        String relname;
      // grammar
              tok = jj_consume_token(Name);
         relname = tok.image;
      args = TypedArguments();
         arity = args.arity();
         rel = new BoolRel(relname,arity,args.types());
         {if (true) return  reader.new ParsedTypedAtom(rel,args);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("TypedAtom");
    }
  }

  final public Vector<String> UntypedArguments() throws ParseException {
    trace_call("UntypedArguments");
    try {
 Vector<String> parsedargs;
      jj_consume_token(12);
      parsedargs = ArgList();
      jj_consume_token(13);
         {if (true) return parsedargs;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("UntypedArguments");
    }
  }

  final public Vector<String> ArgList() throws ParseException {
    trace_call("ArgList");
    try {
 Vector<String> parsedargs = new Vector<String>();
 Token tok;
      if (jj_2_11(3)) {
        tok = jj_consume_token(Name);
                 parsedargs.add(tok.image);
        label_2:
        while (true) {
          if (jj_2_10(3)) {
            ;
          } else {
            break label_2;
          }
          jj_consume_token(14);
          tok = jj_consume_token(Name);
                 parsedargs.add(tok.image);
        }
      } else {
        ;
      }
         {if (true) return parsedargs;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ArgList");
    }
  }

  final public RBNReader3.ParsedTypedArguments TypedArguments() throws ParseException {
    trace_call("TypedArguments");
    try {
        Token tok;
        Vector<String> args = new Vector<String>();
        Vector<Type> types = new Vector<Type>();
        String typename = null;
      jj_consume_token(12);
      if (jj_2_15(3)) {
        if (jj_2_12(3)) {
          typename = TypeDeclaration();
        } else {
          ;
        }
                  if (typename != null)
                        {types.add(new TypeRel(typename));
                         typename = null;
                        }
                  else {types.add(new TypeDomain());}
        tok = jj_consume_token(Name);
                 args.add(tok.image);
        label_3:
        while (true) {
          if (jj_2_13(3)) {
            ;
          } else {
            break label_3;
          }
          jj_consume_token(14);
          if (jj_2_14(3)) {
            typename = TypeDeclaration();
          } else {
            ;
          }
                  if (typename != null)
                        {types.add(new TypeRel(typename));
                         typename = null;
                        }
                  else {types.add(new TypeDomain());}
          tok = jj_consume_token(Name);
                 args.add(tok.image);
        }
      } else {
        ;
      }
      jj_consume_token(13);
         {if (true) return reader.new ParsedTypedArguments(types,args);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("TypedArguments");
    }
  }

  final public String TypeDeclaration() throws ParseException {
    trace_call("TypeDeclaration");
    try {
 Token tok;
      jj_consume_token(15);
      tok = jj_consume_token(Name);
      jj_consume_token(16);
         {if (true) return tok.image;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("TypeDeclaration");
    }
  }

  final public ProbForm Constant() throws ParseException {
    trace_call("Constant");
    try {
 ProbForm parsedpf;
      if (jj_2_16(3)) {
        parsedpf = NumericConstant();
      } else if (jj_2_17(3)) {
        parsedpf = Parameter();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
         {if (true) return parsedpf;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Constant");
    }
  }

  final public ProbFormConstant NumericConstant() throws ParseException {
    trace_call("NumericConstant");
    try {
 ProbFormConstant parsedpfconst;
 Token tok;
      // grammar
              tok = jj_consume_token(Constant);
         parsedpfconst = new ProbFormConstant(Double.parseDouble(tok.image));
         {if (true) return parsedpfconst;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("NumericConstant");
    }
  }

  final public ProbFormConstant Parameter() throws ParseException {
    trace_call("Parameter");
    try {
 ProbFormConstant parsedpfconst;
 Token tok;
      if (jj_2_18(3)) {
        jj_consume_token(17);
        tok = jj_consume_token(Name);
          {if (true) return new ProbFormConstant("#" + tok.image);}
      } else if (jj_2_19(3)) {
        jj_consume_token(18);
        tok = jj_consume_token(Name);
          {if (true) return new ProbFormConstant("$" + tok.image);}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Parameter");
    }
  }

  final public ProbForm Atom() throws ParseException {
    trace_call("Atom");
    try {
 ProbFormAtom parsedpfatom;
 RBNReader3.ParsedUnTypedAtom parsedutat;
 Rel parsedrel;
 Rel oldrel;
      // grammar
              parsedutat = UntypedAtom();
        switch(parseno){
        case 1:
                reader.addAllRel(parsedutat.rel());
                {if (true) return null;}
                break;
        case 2:
                parsedrel = parsedutat.rel();
                // first need to look into reader.probrelsdefined in order 
                // to ensure that the relation associated with the atom 
                // is of type probabilistic
                oldrel = reader.getProbRel(parsedrel);
                // if the following case triggers, then the relation
                // associated with the atom will be predefined
                if (oldrel == null)
                    oldrel = reader.getAllRel(parsedrel);
                {if (true) return new ProbFormAtom(oldrel,parsedutat.args());}
//	 	if (oldrel != null)
//		   return new ProbFormAtom(oldrel,StringOps.stringVectorToArray(parsedutat.args()));
//	 	else {
//		     oldrel = reader.getAllRel(parsedrel);
//		     return new ProbFormBoolAtom(oldrel,StringOps.stringVectorToArray(parsedutat.args()),true);
//		     }
        }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Atom");
    }
  }

  final public ProbFormConvComb ConvCombination() throws ParseException {
    trace_call("ConvCombination");
    try {
 ProbFormConvComb pf;
      if (jj_2_20(3)) {
        pf = ConvCombinationClassic();
      } else if (jj_2_21(3)) {
        pf = ConvCombinationCherry();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2: {if (true) return pf;}
        }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ConvCombination");
    }
  }

  final public ProbFormConvComb ConvCombinationClassic() throws ParseException {
    trace_call("ConvCombinationClassic");
    try {
 ProbForm pf1;
 ProbForm pf2;
 ProbForm pf3;
      jj_consume_token(12);
      pf1 = ProbForm();
      jj_consume_token(19);
      pf2 = ProbForm();
      jj_consume_token(14);
      pf3 = ProbForm();
      jj_consume_token(13);
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2: {if (true) return new ProbFormConvComb(pf1,pf2,pf3);}
        }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ConvCombinationClassic");
    }
  }

  final public ProbFormConvComb ConvCombinationCherry() throws ParseException {
    trace_call("ConvCombinationCherry");
    try {
 ProbForm pf1;
 ProbForm pf2;
 ProbForm pf3;
      jj_consume_token(WIFWIF);
      pf1 = ProbForm();
      jj_consume_token(WIFTHEN);
      pf2 = ProbForm();
      jj_consume_token(WIFELSE);
      pf3 = ProbForm();
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2: {if (true) return new ProbFormConvComb(pf1,pf2,pf3);}
        }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ConvCombinationCherry");
    }
  }

  final public ProbFormCombFunc CombinationFunc() throws ParseException {
    trace_call("CombinationFunc");
    try {
 ProbFormCombFunc pf;
      if (jj_2_22(3)) {
        pf = CombinationFuncClassic();
      } else if (jj_2_23(3)) {
        pf = CombinationFuncCherry();
      } else if (jj_2_24(2147483647)) {
        pf = CombinationFuncSum();
      } else if (jj_2_25(2147483647)) {
        pf = CombinationFuncProd();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2: {if (true) return pf;}
        }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("CombinationFunc");
    }
  }

  final public ProbFormCombFunc CombinationFuncClassic() throws ParseException {
    trace_call("CombinationFuncClassic");
    try {
  Token tok;
  Vector<ProbForm> pflist;
  Vector<String> arglist;
  ProbForm[] pfarr;
  ProbFormBool cc = new ProbFormBoolConstant(true);
      // grammar
              tok = jj_consume_token(CombinationFunction);
      jj_consume_token(20);
      pflist = ProbFormList();
      jj_consume_token(21);
      arglist = ArgList();
      jj_consume_token(19);
      if (jj_2_26(3)) {
        cc = BoolFormula();
      } else {
        ;
      }
      jj_consume_token(22);
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2:
         pfarr = new ProbForm[pflist.size()];
         for (int i=0;i<pfarr.length;i++)
                pfarr[i]=pflist.elementAt(i);
        {if (true) return new ProbFormCombFunc(tok.image,pfarr,StringOps.stringVectorToArray(arglist),cc);}}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("CombinationFuncClassic");
    }
  }

  final public ProbFormCombFunc CombinationFuncCherry() throws ParseException {
    trace_call("CombinationFuncCherry");
    try {
  Token tok;
  Vector<ProbForm> pflist;
  Vector<String> arglist;
  ProbForm[] pfarr;
  ProbFormBool cc = new ProbFormBoolConstant(true);
      jj_consume_token(COMBCOMB);
      pflist = ProbFormList();
      jj_consume_token(COMBWITH);
      tok = jj_consume_token(CombinationFunction);
      jj_consume_token(COMBFORALL);
      arglist = ArgList();
      if (jj_2_27(3)) {
        jj_consume_token(COMBWHERE);
        cc = BoolFormula();
      } else {
        ;
      }
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2:
         pfarr = new ProbForm[pflist.size()];
         for (int i=0;i<pfarr.length;i++)
                pfarr[i]=pflist.elementAt(i);
        {if (true) return new ProbFormCombFunc(tok.image,pfarr,StringOps.stringVectorToArray(arglist),cc);}}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("CombinationFuncCherry");
    }
  }

  final public ProbFormCombFunc CombinationFuncProd() throws ParseException {
    trace_call("CombinationFuncProd");
    try {
 Vector<ProbForm> pflist = new Vector<ProbForm>();
ProbForm nextpf;
ProbForm[] pfarr;
      jj_consume_token(12);
      nextpf = ProbForm();
         pflist.add(nextpf);
      label_4:
      while (true) {
        jj_consume_token(MULT);
        nextpf = ProbForm();
            pflist.add(nextpf);
        if (jj_2_28(3)) {
          ;
        } else {
          break label_4;
        }
      }
      jj_consume_token(13);
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2:
         pfarr = new ProbForm[pflist.size()];
         for (int i=0;i<pfarr.length;i++)
                pfarr[i]=pflist.elementAt(i);
        {if (true) return new ProbFormCombFunc("prod",pfarr,new String[0],new ProbFormBoolConstant(true));}}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("CombinationFuncProd");
    }
  }

  final public ProbFormCombFunc CombinationFuncSum() throws ParseException {
    trace_call("CombinationFuncSum");
    try {
 Vector<ProbForm> pflist = new Vector<ProbForm>();
ProbForm nextpf;
ProbForm[] pfarr;
      jj_consume_token(12);
      nextpf = ProbForm();
         pflist.add(nextpf);
      label_5:
      while (true) {
        jj_consume_token(PLUS);
        nextpf = ProbForm();
            pflist.add(nextpf);
        if (jj_2_29(3)) {
          ;
        } else {
          break label_5;
        }
      }
      jj_consume_token(13);
         switch(parseno){
        case 1:
                {if (true) return null;}
                break;
        case 2:
         pfarr = new ProbForm[pflist.size()];
         for (int i=0;i<pfarr.length;i++)
                pfarr[i]=pflist.elementAt(i);
        {if (true) return new ProbFormCombFunc("sum",pfarr,new String[0],new ProbFormBoolConstant(true));}}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("CombinationFuncSum");
    }
  }

  final public Vector<ProbForm> ProbFormList() throws ParseException {
    trace_call("ProbFormList");
    try {
 Vector<ProbForm> pflist = new Vector<ProbForm>();
 ProbForm nextpf;
      if (jj_2_31(3)) {
        nextpf = ProbForm();
           pflist.add(nextpf);
        label_6:
        while (true) {
          if (jj_2_30(3)) {
            ;
          } else {
            break label_6;
          }
          jj_consume_token(14);
          nextpf = ProbForm();
           pflist.add(nextpf);
        }
      } else {
        ;
      }
         {if (true) return pflist;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ProbFormList");
    }
  }

  final public ProbFormBool BoolFormula() throws ParseException {
    trace_call("BoolFormula");
    try {
 ProbFormBool pf;
      if (jj_2_32(2147483647)) {
        pf = BoolAtom();
      } else if (jj_2_33(2147483647)) {
        pf = BoolEquality();
      } else if (jj_2_34(3)) {
        pf = BoolNegation();
      } else if (jj_2_35(2147483647)) {
        pf = BoolAnd();
      } else if (jj_2_36(2147483647)) {
        pf = BoolOr();
      } else if (jj_2_37(3)) {
        pf = BoolConstant();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
     {if (true) return pf;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("BoolFormula");
    }
  }

  final public ProbFormBoolAtom BoolAtom() throws ParseException {
    trace_call("BoolAtom");
    try {
 RBNReader3.ParsedUnTypedAtom parsedat;
      // grammar
              parsedat = UntypedAtom();
         {if (true) return new ProbFormBoolAtom(parsedat.rel(),parsedat.args(),true);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("BoolAtom");
    }
  }

  final public ProbFormBoolEquality BoolEquality() throws ParseException {
    trace_call("BoolEquality");
    try {
 Token tok1;
 Token tok2;
      // grammar
              tok1 = jj_consume_token(Name);
      jj_consume_token(10);
      tok2 = jj_consume_token(Name);
         {if (true) return new ProbFormBoolEquality(tok1.image,tok2.image,true);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("BoolEquality");
    }
  }

  final public ProbFormBoolComposite BoolAnd() throws ParseException {
    trace_call("BoolAnd");
    try {
 Vector<ProbFormBool> comps=new Vector<ProbFormBool>() ;
ProbFormBool nextpfb;
      jj_consume_token(12);
      nextpfb = BoolFormula();
         comps.add(nextpfb);
      label_7:
      while (true) {
        jj_consume_token(23);
        nextpfb = BoolFormula();
            comps.add(nextpfb);
        if (jj_2_38(3)) {
          ;
        } else {
          break label_7;
        }
      }
      jj_consume_token(13);
 {if (true) return new ProbFormBoolComposite(comps,ProbFormBool.OPERATORAND,true);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("BoolAnd");
    }
  }

  final public ProbFormBoolComposite BoolOr() throws ParseException {
    trace_call("BoolOr");
    try {
 Vector<ProbFormBool> comps=new Vector<ProbFormBool>();
ProbFormBool nextpfb;
      jj_consume_token(12);
      nextpfb = BoolFormula();
         comps.add(nextpfb);
      label_8:
      while (true) {
        jj_consume_token(21);
        nextpfb = BoolFormula();
            comps.add(nextpfb);
        if (jj_2_39(3)) {
          ;
        } else {
          break label_8;
        }
      }
      jj_consume_token(13);
 {if (true) return new ProbFormBoolComposite(comps,ProbFormBool.OPERATOROR,true);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("BoolOr");
    }
  }

  final public ProbFormBoolConstant BoolConstant() throws ParseException {
    trace_call("BoolConstant");
    try {
      if (jj_2_40(3)) {
        jj_consume_token(24);
                 {if (true) return new ProbFormBoolConstant(true);}
      } else if (jj_2_41(3)) {
        jj_consume_token(25);
                 {if (true) return new ProbFormBoolConstant(false);}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("BoolConstant");
    }
  }

  final public ProbFormBool BoolNegation() throws ParseException {
    trace_call("BoolNegation");
    try {
 ProbFormBool pfb;
      jj_consume_token(26);
      pfb = BoolFormula();
   pfb.toggleSign();
  {if (true) return pfb;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("BoolNegation");
    }
  }

  final public ProbFormMacroCall MacroCall() throws ParseException {
    trace_call("MacroCall");
    try {
 RBNReader3.ParsedUnTypedAtom parsedat;
 RBNMacro macrodef;
      jj_consume_token(9);
      parsedat = UntypedAtom();
        // Add the '@' back to the name:
        parsedat.set_relname("@"+parsedat.rel().name());
        switch(parseno){
                case 1:
                        {if (true) return null;}
                        break;
                case 2:
                        macrodef = reader.getMacroDef(parsedat.rel());
                        if (macrodef != null)
                        {if (true) return new ProbFormMacroCall(macrodef,parsedat.args());}
          else {if (true) throw new ParseException("Macro @" + parsedat.rel().name.name + " undefined");}
                }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("MacroCall");
    }
  }

// Java functions
  final public void setReader(RBNReader3 rdr) throws ParseException {
    trace_call("setReader");
    try {
         reader = rdr;
    } finally {
      trace_return("setReader");
    }
  }

  final public void setParseno(int pn) throws ParseException {
    trace_call("setParseno");
    try {
         parseno = pn;
    } finally {
      trace_return("setParseno");
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(12)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_15()) jj_scanpos = xsp;
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(9)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(14)) return true;
    if (jj_scan_token(Name)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(CombinationFunction)) return true;
    if (jj_scan_token(20)) return true;
    if (jj_3R_37()) return true;
    if (jj_scan_token(21)) return true;
    if (jj_3R_47()) return true;
    if (jj_scan_token(19)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_26()) jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(Name)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_10()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_47() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(26)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_41() {
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3_40() {
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_40()) {
    jj_scanpos = xsp;
    if (jj_3_41()) return true;
    }
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_47()) return true;
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_39() {
    if (jj_scan_token(21)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_15()) return true;
    Token xsp;
    if (jj_3_39()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_39()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(Name)) return true;
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3_38() {
    if (jj_scan_token(23)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(WIFWIF)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(WIFTHEN)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(WIFELSE)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_15()) return true;
    Token xsp;
    if (jj_3_38()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_38()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(Name)) return true;
    if (jj_3R_42()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(Name)) return true;
    if (jj_scan_token(10)) return true;
    if (jj_scan_token(Name)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(19)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(14)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3_36() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(21)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3_9()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_35() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(23)) return true;
    return false;
  }

  private boolean jj_3_33() {
    if (jj_scan_token(Name)) return true;
    if (jj_scan_token(10)) return true;
    return false;
  }

  private boolean jj_3_32() {
    if (jj_scan_token(Name)) return true;
    if (jj_scan_token(12)) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_37() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) return true;
    }
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3_34() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3_37()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_30() {
    if (jj_scan_token(14)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3_31() {
    if (jj_3R_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_31()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(9)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_3() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3_2()) return true;
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_29() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_26()) return true;
    Token xsp;
    if (jj_3_29()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_29()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(Name)) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_scan_token(17)) return true;
    if (jj_scan_token(Name)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) return true;
    }
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(Constant)) return true;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_scan_token(MULT)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(12)) return true;
    if (jj_3R_26()) return true;
    Token xsp;
    if (jj_3_28()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_28()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) return true;
    }
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(15)) return true;
    if (jj_scan_token(Name)) return true;
    if (jj_scan_token(16)) return true;
    return false;
  }

  private boolean jj_3_27() {
    if (jj_scan_token(COMBWHERE)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(COMBCOMB)) return true;
    if (jj_3R_37()) return true;
    if (jj_scan_token(COMBWITH)) return true;
    if (jj_scan_token(CombinationFunction)) return true;
    if (jj_scan_token(COMBFORALL)) return true;
    if (jj_3R_47()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_27()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(14)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) jj_scanpos = xsp;
    if (jj_scan_token(Name)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) jj_scanpos = xsp;
    if (jj_scan_token(Name)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_13()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  /** Generated Token Manager. */
  public RBNParser3TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[41];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public RBNParser3(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RBNParser3(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RBNParser3TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public RBNParser3(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RBNParser3TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public RBNParser3(RBNParser3TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(RBNParser3TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[41];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 41; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  private int trace_indent = 0;
  private boolean trace_enabled = false;

/** Enable tracing. */
  final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
    trace_enabled = false;
  }

  private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 41; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
