name: Build and Release primula3.jar

on:
  push:
    branches:
      - master
    paths:
      - 'Source/**'      
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x ./Source/gradlew

      - name: Build JAR
        run: ./gradlew jar
        working-directory: ./Source
          
      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Primula JAR
          files: JAR/primula.jar
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
